/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CharactersImport } from './routes/characters'
import { Route as IndexImport } from './routes/index'
import { Route as CharactersCharacterIdImport } from './routes/characters.$characterId'
import { Route as CharactersCharacterIdCampaignsCampaignIdImport } from './routes/characters.$characterId.campaigns.$campaignId'

// Create/Update Routes

const CharactersRoute = CharactersImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CharactersCharacterIdRoute = CharactersCharacterIdImport.update({
  id: '/$characterId',
  path: '/$characterId',
  getParentRoute: () => CharactersRoute,
} as any)

const CharactersCharacterIdCampaignsCampaignIdRoute =
  CharactersCharacterIdCampaignsCampaignIdImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => CharactersCharacterIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersImport
      parentRoute: typeof rootRoute
    }
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdImport
      parentRoute: typeof CharactersImport
    }
    '/characters/$characterId/campaigns/$campaignId': {
      id: '/characters/$characterId/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/characters/$characterId/campaigns/$campaignId'
      preLoaderRoute: typeof CharactersCharacterIdCampaignsCampaignIdImport
      parentRoute: typeof CharactersCharacterIdImport
    }
  }
}

// Create and export the route tree

interface CharactersCharacterIdRouteChildren {
  CharactersCharacterIdCampaignsCampaignIdRoute: typeof CharactersCharacterIdCampaignsCampaignIdRoute
}

const CharactersCharacterIdRouteChildren: CharactersCharacterIdRouteChildren = {
  CharactersCharacterIdCampaignsCampaignIdRoute:
    CharactersCharacterIdCampaignsCampaignIdRoute,
}

const CharactersCharacterIdRouteWithChildren =
  CharactersCharacterIdRoute._addFileChildren(
    CharactersCharacterIdRouteChildren,
  )

interface CharactersRouteChildren {
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRouteWithChildren
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersCharacterIdRoute: CharactersCharacterIdRouteWithChildren,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/characters/$characterId': typeof CharactersCharacterIdRouteWithChildren
  '/characters/$characterId/campaigns/$campaignId': typeof CharactersCharacterIdCampaignsCampaignIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/characters/$characterId': typeof CharactersCharacterIdRouteWithChildren
  '/characters/$characterId/campaigns/$campaignId': typeof CharactersCharacterIdCampaignsCampaignIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/characters/$characterId': typeof CharactersCharacterIdRouteWithChildren
  '/characters/$characterId/campaigns/$campaignId': typeof CharactersCharacterIdCampaignsCampaignIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/characters/$characterId'
    | '/characters/$characterId/campaigns/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/characters/$characterId'
    | '/characters/$characterId/campaigns/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/characters/$characterId'
    | '/characters/$characterId/campaigns/$campaignId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/characters"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/characters": {
      "filePath": "characters.tsx",
      "children": [
        "/characters/$characterId"
      ]
    },
    "/characters/$characterId": {
      "filePath": "characters.$characterId.tsx",
      "parent": "/characters",
      "children": [
        "/characters/$characterId/campaigns/$campaignId"
      ]
    },
    "/characters/$characterId/campaigns/$campaignId": {
      "filePath": "characters.$characterId.campaigns.$campaignId.tsx",
      "parent": "/characters/$characterId"
    }
  }
}
ROUTE_MANIFEST_END */
