/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CharactersListImport } from './routes/characters-list'
import { Route as IndexImport } from './routes/index'
import { Route as CharacterIdImport } from './routes/character.$id'
import { Route as CampaignCharacterIdCampaignIdImport } from './routes/campaign.$characterId.$campaignId'

// Create/Update Routes

const CharactersListRoute = CharactersListImport.update({
  id: '/characters-list',
  path: '/characters-list',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CharacterIdRoute = CharacterIdImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRoute,
} as any)

const CampaignCharacterIdCampaignIdRoute =
  CampaignCharacterIdCampaignIdImport.update({
    id: '/campaign/$characterId/$campaignId',
    path: '/campaign/$characterId/$campaignId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/characters-list': {
      id: '/characters-list'
      path: '/characters-list'
      fullPath: '/characters-list'
      preLoaderRoute: typeof CharactersListImport
      parentRoute: typeof rootRoute
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdImport
      parentRoute: typeof rootRoute
    }
    '/campaign/$characterId/$campaignId': {
      id: '/campaign/$characterId/$campaignId'
      path: '/campaign/$characterId/$campaignId'
      fullPath: '/campaign/$characterId/$campaignId'
      preLoaderRoute: typeof CampaignCharacterIdCampaignIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters-list': typeof CharactersListRoute
  '/character/$id': typeof CharacterIdRoute
  '/campaign/$characterId/$campaignId': typeof CampaignCharacterIdCampaignIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters-list': typeof CharactersListRoute
  '/character/$id': typeof CharacterIdRoute
  '/campaign/$characterId/$campaignId': typeof CampaignCharacterIdCampaignIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/characters-list': typeof CharactersListRoute
  '/character/$id': typeof CharacterIdRoute
  '/campaign/$characterId/$campaignId': typeof CampaignCharacterIdCampaignIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters-list'
    | '/character/$id'
    | '/campaign/$characterId/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters-list'
    | '/character/$id'
    | '/campaign/$characterId/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/characters-list'
    | '/character/$id'
    | '/campaign/$characterId/$campaignId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersListRoute: typeof CharactersListRoute
  CharacterIdRoute: typeof CharacterIdRoute
  CampaignCharacterIdCampaignIdRoute: typeof CampaignCharacterIdCampaignIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersListRoute: CharactersListRoute,
  CharacterIdRoute: CharacterIdRoute,
  CampaignCharacterIdCampaignIdRoute: CampaignCharacterIdCampaignIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/characters-list",
        "/character/$id",
        "/campaign/$characterId/$campaignId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/characters-list": {
      "filePath": "characters-list.tsx"
    },
    "/character/$id": {
      "filePath": "character.$id.tsx"
    },
    "/campaign/$characterId/$campaignId": {
      "filePath": "campaign.$characterId.$campaignId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
